[package]
name = "http2socks"
version = "0.1.0"
license = "MIT"
repository = "https://github.com/cssivision/http2socks"
homepage = "https://github.com/cssivision/http2socks"
authors = ["cssivision <cssivision@gmail.com>"]
description = "http to socks proxy."
readme = "README.md"
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
http = "0.2"
