[package]
name = "http2socks"
version = "0.1.0"
license = "MIT"
repository = "https://github.com/cssivision/http2socks"
homepage = "https://github.com/cssivision/http2socks"
authors = ["cssivision <cssivision@gmail.com>"]
description = "http to socks proxy."
readme = "README.md"

[[bin]]
name = "http2socks"
path = "src/bin/main.rs"

[dependencies]
futures = "0.1.14"
tokio-core = "0.1.9"
tokio-io = "0.1.3"
num = "0.1.40"
futures-cpupool = "0.1.5"
tokio-timer = "0.1.2"
